//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolIDDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class toolid
    {
        public int TransactionID { get; set; }
        public int CategoryID { get; set; }
        public string ToolID1 { get; set; }
    }
}
